Update installation instructions for FreeBSD
Detect if curl, fetch (FreeBSD), or wget are installed, and use the first
found.

Put wget options before operands in the case of non-GNU environment,
or a GNU environment with the POSIXLY_CORRECT environment variable set.

diff --git a/dependencies/common/install-boost b/dependencies/common/install-boost
--- a/dependencies/common/install-boost
+++ b/dependencies/common/install-boost
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env sh
 
 #
 # install-boost
@@ -22,6 +22,7 @@ INSTALL_DIR=`pwd`
 
 # determine platform
 PLATFORM=`uname`
+alias sudo=$(command -v sudo) # null string if sudo does not exist
 
 # vars
 BOOST_VERSION_NUMBER=1.50.0
@@ -35,15 +36,13 @@ if ! test -e $BOOST_DIR
 then
    # download boost
    BOOST_URL=http://sourceforge.net/projects/boost/files/boost/$BOOST_VERSION_NUMBER/$BOOST_TAR/download?use_mirror=autoselect
-   if [ "$PLATFORM" == "Darwin" ]
-   then
-      curl -L $BOOST_URL > $BOOST_TAR
-   else
-      wget $BOOST_URL -O $BOOST_TAR
-   fi
-   
-   # remove existing boost installation
-   sudo rm -rf $BOOST_DIR
+   # use first command found
+   case $(command -v curl || command -v fetch || command -v wget) in
+     *curl)  curl -L $BOOST_URL > $BOOST_TAR ;;
+     *fetch) fetch -o $BOOST_TAR $BOOST_URL ;;
+     *wget)  wget -O $BOOST_TAR $BOOST_URL ;;
+     *)      echo 'ERROR: need curl, fetch, or wget' 1>&2; exit 1 ;;
+   esac
   
    # untar source (remove existing)
    sudo rm -rf $BOOST_BUILD_DIR
diff --git a/dependencies/common/install-mathjax b/dependencies/common/install-mathjax
--- a/dependencies/common/install-mathjax
+++ b/dependencies/common/install-mathjax
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env sh
 
 #
 # install-mathjax
@@ -20,18 +20,15 @@ set -e
 # install dir
 INSTALL_DIR=`pwd`
 
-# determine platform
-PLATFORM=`uname`
-
-# use curl or wget as appropriate
+# use curl, fetch, or wget
 download()
 {
-  if [ "$PLATFORM" == "Darwin" ]
-  then
-    curl -L https://s3.amazonaws.com/rstudio-buildtools/$1 > $1
-  else
-    wget https://s3.amazonaws.com/rstudio-buildtools/$1 -O $1
-  fi
+  case $(command -v curl || command -v fetch || command -v wget) in
+    *curl)  curl -LO https://s3.amazonaws.com/rstudio-buildtools/$1 ;;
+    *fetch) fetch https://s3.amazonaws.com/rstudio-buildtools/$1 ;;
+    *wget)  wget -O $1 https://s3.amazonaws.com/rstudio-buildtools/$1 ;;
+    *)      echo 'ERROR: need curl, fetch, or wget' 1>&2; exit 1 ;;
+  esac
 }
 
 # download and extract mathjax if necessary
